### ISSUE TITLE
Add checks before attempting table updates

### ISSUE THREAD

**Issue by mhglover** [CarnegieLearningWeb/educational-experiment-service#64]
During startup we're seeing the application attempt to add the uniquifier column to the log table and fail because the column already exists.  Once it gets into this state, I've only been able to get it running again by wiping the database.  Here's an excerpt from a log:

```
0 migrations are already loaded in the database.
2 migrations were found in the source code.
2 migrations are new migrations that needs to be executed.
query: START TRANSACTION
query: ALTER TABLE "log" ADD "uniquifier" character varying NOT NULL DEFAULT 1
query failed: ALTER TABLE "log" ADD "uniquifier" character varying NOT NULL DEFAULT 1
error: error: column "uniquifier" of relation "log" already exists
    at Connection.parseE (/usr/src/app/packages/Upgrade/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/usr/src/app/packages/Upgrade/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/usr/src/app/packages/Upgrade/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:203:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  name: 'error',
  length: 132,
  severity: 'ERROR',
  code: '42701',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '5882',
  routine: 'check_for_column_name_collision'
}
query: ROLLBACK
(node:64) UnhandledPromiseRejectionWarning: Error: Database auth fail
    at /usr/src/app/packages/Upgrade/dist/src/loaders/typeormLoader.js:36:19
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/packages/Upgrade/node_modules/tslib/tslib.js:113:69)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:64) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:64) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm not sure why it's also reporting a database authorization failure -- the error from postgres doesn't appear to be authorization related.

**Comment by VivekFitkariwala** [comment]
Error handler need to be updated with specific error message.

One thing which we need to update from our end is having a single migration script which will create the tables. At present I think your Environment Variable TYPEORM_SYNCHRONIZE is true and it is creating/updating the tables which is not ideal for production environment.

**Comment by mhglover** [comment]
We did have `TYPEORM_SYNCHRONIZE=true`.  I've now tested it set to `false`, but the application crashes with the same issue.

**Comment by VivekFitkariwala** [comment]
It will not resolve the issue as we will need the migration script to fix this. Once the migration script is pushed you need to recreate the environment. I will update you once that is done from our end.

**Comment by mhglover** [comment]
Thanks Vivek!  Any idea when we'll get that?  This is a blocker for QA testing.

**Comment by VivekFitkariwala** [comment]
Hi Matt, code is updated with single migration script and test cases will use the same migration script. You need to recreate the environment with update tsvar file here is the sample
```
# General variables
current_directory       = "staging"
aws_region              = "us-east-1"
environment             = "staging"
prefix                  = "upgrade" 
app_version             = "1.0.0"
aws_profile             = "playpower"

# RDS related details 
allocated_storage       = 100
engine_version          = "11.5"
identifier              = "dev-postgres" 
instance_class          = "db.t2.micro"
storage_type            = "gp2"
multi_az                = "false"

# EBS instance details
app_instance_type       = "t2.micro"
ebs_app_name            = "upgrade-experiment-app"
autoscaling_min_size    =  1 
autoscaling_max_size    =  1 

# APP environment variables
GOOGLE_CLIENT_ID        = "135765367152-pq4jhd3gra10jda9l6bpnmu9gqt48tup.apps.googleusercontent.com"
DOMAIN_NAME             = "carnegielearning.com"
MONITOR_PASSWORD        = "****"
SWAGGER_PASSWORD        = "****"
TYPEORM_SYNCHRONIZE     = false
TOKEN_SECRET_KEY        = "******"
AUTH_CHECK              = false

# CICD variables
repository_name         = "educational-experiment-service"
branch_name             = "staging"
build_image             = "aws/codebuild/standard:1.0"
build_compute_type      =  "BUILD_GENERAL1_LARGE"
privileged_mode         =  true
```
Let me know if you face any issue

**Comment by nirmalpatel** [comment]
@mhglover We have implemented the TypeORM migration scripts. Should we close this issue now?
